import type { Metadata } from "next";
import { Header } from "@/components/shared";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Sushi-BOOM | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen ">
      <Header />
      {children}
      {modal}
      <Toaster />
    </main>
  );
}
